eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:9101/eureka/


logging:
  level:
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
server:
  port: 9103

app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: l0lzb1d9Btx040gchwDalxJyeqnaQnS3
    realm: em-auth-srver
    serverUrl: http://localhost:9081
keycloak:
  realm: user-management
  client-id: admin-cli
  client-secret: gsvEPn43brtmQp0T5mGTF9YP8QSMHKZm
  token-uri: http://localhost:9081/realms/master/protocol/openid-connect/token
  base-url: http://localhost:9081/admin/realms/user-management


